Repository stevespringett/Alpine, pull requests merged in 2024-12, with the labels that each got.

#726 Prevent enumeration of managed users through timing attacks
  alpine-server/src/main/java/alpine/server/auth/ManagedUserAuthenticationService.java
  alpine-server/src/test/java/alpine/server/auth/ManagedUserAuthenticationServiceTest.java
Labels: defect

#722 Allow PROPERTYVALUE to be bigger than 1024
  alpine-model/src/main/java/alpine/model/ConfigProperty.java
Labels: enhancement

#737 Bump micrometer to 1.14.2
  alpine-common/pom.xml
  alpine-common/src/main/java/alpine/common/metrics/Metrics.java
  alpine-server/src/main/java/alpine/server/servlets/MetricsServlet.java
  alpine-server/src/test/java/alpine/server/servlets/MetricsServletTest.java
  pom.xml
Labels: dependencies
